dist: trusty
sudo: required

language: ruby

rvm:
  - 2.3.1

branches:
  only:
    - master

before_install:
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  - node -v

script:
  - yarn install && node buildComponents.js
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --url-swap "^/magento:" --only-4xx --allow-hash-href

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer