dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

branches:
  only:
    - master

cache: bundler

before_install:
  - rvm install 2.3.1
  - bundle install
  - yarn install && node buildComponents.js
  - bundle exec jekyll build

script:
  - bundle exec htmlproofer ./_site --url-swap "^/magento:" --only-4xx --allow-hash-href

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer