m1_version: 1.8.0
m2_version: 1.0.5

# Site settings
title: Magento Search Extension Powered by Algolia
magento2Title: Magento 2 Search Extension Powered by Algolia
description: Power your Magento store search with Algolia. The fastest way to increase conversions on your site with instant search, autocomplete, and real time results.

twitter_username: algolia
github_username: algolia
host: 0.0.0.0

# Navigation
navigation:
 - text: FAQ
   url: /faq/
 - text: About
   url: /about/

# Build settings
source: _src

markdown: kramdown
kramdown:
  input: GFM

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

exclude:
  - headers

# Assets
sass:
  sass_dir: css

gems:
  - jekyll-redirect-from
